name: Build and run tests

on: [push, pull_request]

env:
  app_id: inputstream.adaptive

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kodi repo
        uses: actions/checkout@v4
        with:
          repository: xbmc/xbmc
          ref: master
          path: xbmc
      - name: Checkout add-on repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.app_id }}
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:team-xbmc/xbmc-nightly
          sudo apt-get update
          sudo apt-get install -y gcc g++ fakeroot
      - name: Configure
        run: |
          cd ${{ env.app_id }}
          mkdir -p build
          cd build
          cmake -DADDONS_TO_BUILD=${{ env.app_id }} -DADDON_SRC_PREFIX=${{ github.workspace }} -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/xbmc/addons -DPACKAGE_ZIP=1 ${{ github.workspace }}/xbmc/cmake/addons
      - name: Build
        run: |
          cd ${{ env.app_id }}/build
          make
      - name: Run tests
        run: |
          cd ${{ env.app_id }}/build/${{ env.app_id }}-prefix/src/${{ env.app_id }}-build
          make CTEST_OUTPUT_ON_FAILURE=1 GTEST_COLOR=1 test

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Kodi repo
        uses: actions/checkout@v4
        with:
          repository: xbmc/xbmc
          ref: master
          path: xbmc
      - name: Checkout add-on repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.app_id }}
      - name: Install dependencies
        run: |
          choco install -y ninja cmake
      - name: Configure
        run: |
          mkdir -p ${{ env.app_id }}/build
          cd ${{ env.app_id }}/build
          cmake -G "Ninja" -DADDONS_TO_BUILD=${{ env.app_id }} -DADDON_SRC_PREFIX=${{ github.workspace }} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/xbmc/addons -DPACKAGE_ZIP=1 ${{ github.workspace }}/xbmc/cmake/addons
      - name: Build
        run: |
          cd ${{ env.app_id }}/build
          ninja
      - name: Run tests
        run: |
          cd ${{ env.app_id }}/build/${{ env.app_id }}-prefix/src/${{ env.app_id }}-build
          ctest -C Release -V
